<?php

namespace App\Models;

use CodeIgniter\Model;

class UserDetailsModel extends Model
{
    protected $table = 'user_details';

    protected $primaryKey = 'employee_id';
    protected $allowedFields = ['user_id', 'first_name', 'last_name', 'gender', 'contact_number', 'date_of_birth', 'date_of_joining', 'nationality'];

    // Ensure 'employee_id' is autogenerated by the database
    protected $useAutoIncrement = true;
}
